// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from "storyblok";
export interface HeaderStoryblok {
  content?: string;
  className?: string;
  component: "header";
  _uid: string;
  [k: string]: any;
}

export interface PageStoryblok {
  body?: (HeaderStoryblok | PageStoryblok)[];
  component: "page";
  _uid: string;
  [k: string]: any;
}
